INSERT INTO Actors(Actor_name)
	VALUES 
		('Joel Kinnaman'),
		('James Purefoy'),
		('Martha Higareda'), 
		('Chris Conner'),
		('Dichen Lachman'), 
		('Ato Essandoh'),
		('Kristin Lehman'), 
		('Trieu Tran'),
		('Renée Elise Goldsberry'),
		('Molly Parker'), 
		('Toby Stephens'),
		('Maxwell Jenkins'),
		('Taylor Russell'), 
		('Mina Sundwall'),
		('Ignacio Serricchio'),
		('Parker Posey'),
		('Abbi Jacobson'),
		('Eric Andre'),
		('Nat Faxon'),
		('John DiMaggio'),
		('Tress MacNeille'),
		('Matt Berry'),
		('David Herman'),
		('Maurice LaMarche'),
		('Lucy Montgomery'),
		('Billy West'),
		('Noel Fielding'),
		('Sharon Horgan'),
		('Emma Stone'),
		('Jonah Hill'),
		('Justin Theroux'),
		('Sonoya Mizuno'),
		('Gabriel Byrne'),
		('Sally Field'),
		('Kiernan Shipka'), 
		('Jaz Sinclair'),
		('Michelle Gomez'),
		('Chance Perdomo'),
		('Lucy Davis'),
		('Miranda Otto'),
		('Richard Coyle'),
		('Ross Lynch'), 
		('Tati Gabrielle')





